### PR TITLE
update controller-runtime to v0.7

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
This PR updates to controller-runtime v0.7,
I needed to push this because on the installer project the providers ported to v0.7, but because baremetal-operator didn't then we hit a dependency problem when updating the installer dependencies, see https://github.com/openshift/installer/pull/4700.

### CODE REVIEW

**Comment by dhellmann** [comment]
/hold

This repo is a downstream fork of https://github.com/metal3-io/baremetal-operator so this PR needs to be applied there before it's applied here.

**Comment by Gal-Zaidman** [comment]
> /hold
> 
> This repo is a downstream fork of https://github.com/metal3-io/baremetal-operator so this PR needs to be applied there before it's applied here.

Thanks, good to know

**Comment by Gal-Zaidman** [comment]
Pushing to upstream, I guess you can port it to this repo according to your process

**Pull request closed without merging**
