### PR TITLE
Bug 1799219: Verify CA

### PR DESCRIPTION
**Pull request by honza**
cherry-picked from https://github.com/metal3-io/baremetal-operator/pull/396

### CODE REVIEW

**Comment by stbenjam** [comment]
I think you're missing 06ea4ac61d976ce8170d66501eff584b93d543ff

**Comment by honza** [comment]
@stbenjam fixed, the cherry pick range apparently isn't inclusive

**Comment by stbenjam** [comment]
Looks right to me! Since I contributed to the upstream PR I probably shouldn't lgtm/approve it. @zaneb @dhellmann Would you all mind taking a look? Thanks!

/assign @zaneb
/cc @dhellmann

**Comment by dhellmann** [comment]
Previously we've just merged upstream into this repo instead of using cherry-picking because it means we have fewer merge conflicts to deal with. Did you want to do this as a cherry-pick to make backporting it easier?

**Comment by stbenjam** [comment]
Do you mean to merge every change from baremetal-operator into this repo? I guess to follow the proper openshift process at this point, we can't just pull in every change from upstream into the 4.4 branches, but rather has to be discrete features tied to a specific BZ.

**Comment by dhellmann** [comment]
> Do you mean to merge every change from baremetal-operator into this repo? I guess to follow the proper openshift process at this point, we can't just pull in every change from upstream into the 4.4 branches, but rather has to be discrete features tied to a specific BZ.

Yeah, I used to literally merge from one remote to another in my local repo then push a branch to create a PR here. If we have to do them 1 by 1 now, that's OK. The changes here look fine to me.

**Comment by stbenjam** [comment]
I think I'd rather do them one at a time to follow the rest of openshift.  We can resume merging once `master` is open again per OpenShift policies, git should exclude anything we cherry-picked right?

This the diff:
https://github.com/openshift/baremetal-operator/compare/master...metal3-io:master 

Most of the changes don't affect us since it's touching the deploy/ dir, but I'm not sure we want to enable fast-track for example.

**Comment by dhellmann** [comment]
OK, that all makes sense.

/lgtm

**Pull request merged**
