### PR TITLE
Upstream Rebase

### PR DESCRIPTION
**Pull request by patrickdillon**
Particularly, pull in 21a55b1528d00190777d140dc015cd8555661ddb to simplify dependency management

### CODE REVIEW

**Comment by patrickdillon** [comment]
Hm. Trying to figure out how to properly vendor

**Comment by zaneb** [comment]
Need to merge to master first, then revendor.

**Comment by patrickdillon** [comment]
merged and then vendored. I put the vendoring in a separate commit dcdd5baee3fadbf7d0cfaf0a399344935c90eaf1 LMK if there is another way of doing it

**Comment by patrickdillon** [comment]
spoke too soon, tests are still failing :eyes:

**Comment by zaneb** [comment]
You might need to merge in the other direction.

**Comment by dtantsur** [comment]
/approve

Looks correct to me. Will need a bug to get merged.

**Pull request merged**
