### PR TITLE
Fix hosts with infraenv getting stuck in inspection

### PR DESCRIPTION
**Pull request by dtantsur**
Currently, if you set an infraenv label on a host, image-customization-controller will skip handling the associated image. A new assisted controller will handle them instead. If this controller is absent, the host will get stuck in inspection/preparing even if inspection is disabled.

This PR backports two upstream changes:
- Get rid of a separate state for profile matching
- Skip the inspecting state when inspection is disabled
- Do not consider empty RAID and root device hints updated

On top of that, a downstream-only hack is applied to avoid backporting a large refactoring:
- [OCP 4.11] Skip preparing when inspection is disabled

This does break users that won't BIOS settings but no inspection. We're not aware of such requests, so we think we can live with that for 4.11.

### CODE REVIEW

**Comment by zaneb** [comment]
Possible alternative: #229.

**Comment by dtantsur** [comment]
Closing in favour of https://github.com/openshift/baremetal-operator/pull/229

**Pull request closed without merging**
