### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by dhellmann**
This PR was created with "git merge -s ours master" where master refers to master in the metal3-io/baremetal-operator repo. All of the code changes have been made locally already using cherry-picked commits. The "ours" merge strategy is used to avoid having to resolve conflicts with commits we want to skip, like the dependency updates. This PR is intended to make future merges of real change easier, so we can stop individually cherry-picking commits from upstream into this repository.

### CODE REVIEW

**Comment by russellb** [comment]
Did you do anything to validate nothing got missed by accident?  I see a whole bunch of commits listed that we'd want, but when I checked them, they were ones we merged via cherry-pick.  Any thoughts on how we can easily validate we're not accidentally skipping some changes?

**Comment by dhellmann** [comment]
> Did you do anything to validate nothing got missed by accident? I see a whole bunch of commits listed that we'd want, but when I checked them, they were ones we merged via cherry-pick. Any thoughts on how we can easily validate we're not accidentally skipping some changes?

I checked a while ago, but I can do that again. We would need to treat those as cherry-picks, though. The point of this commit is to bring this repo into a state where we can start merging normally again because the dependency updates will be ignored.

**Comment by russellb** [comment]
> > Did you do anything to validate nothing got missed by accident? I see a whole bunch of commits listed that we'd want, but when I checked them, they were ones we merged via cherry-pick. Any thoughts on how we can easily validate we're not accidentally skipping some changes?
> 
> I checked a while ago, but I can do that again. We would need to treat those as cherry-picks, though. The point of this commit is to bring this repo into a state where we can start merging normally again because the dependency updates will be ignored.

OK it looks fine to me if you checked the commits.  I guess we'll need to do this each time we do a conflicting vendor update?

/lgtm

**Comment by dhellmann** [comment]
> > > Did you do anything to validate nothing got missed by accident? I see a whole bunch of commits listed that we'd want, but when I checked them, they were ones we merged via cherry-pick. Any thoughts on how we can easily validate we're not accidentally skipping some changes?
> > 
> > 
> > I checked a while ago, but I can do that again. We would need to treat those as cherry-picks, though. The point of this commit is to bring this repo into a state where we can start merging normally again because the dependency updates will be ignored.
> 
> OK it looks fine to me if you checked the commits. I guess we'll need to do this each time we do a conflicting vendor update?
> 
> /lgtm

Yes, although now that I know to do it we can just do it as soon as we have the change upstream that we don't want downstream so it should be clearer what we're doing.

**Pull request merged**
