### PR TITLE
Bug 1986656: Fix missing case of BuildRAIDCleanSteps

### PR DESCRIPTION
**Pull request by Hellcatlk**
I will pick up the upstream PRs after that has been merged, and will add that commits into this one. 
URL of upstream PRs are as follows.
 - https://github.com/metal3-io/baremetal-operator/pull/942

Therefore, please pend the review of this PR.

### CODE REVIEW

**Comment by hardys** [comment]
@Hellcatlk thanks for the PR - typically we do periodic rebases to pick up merged PRs from the upstream BMO repo (see recent closed PRs from @honza) so it may be best to follow that process again here I think?

**Comment by Hellcatlk** [comment]
> @Hellcatlk thanks for the PR - typically we do periodic rebases to pick up merged PRs from the upstream BMO repo (see recent merged PRs from @honza) so it may be best to follow that process again here I think?

understood, thanks for reminding, I will hold this PR

**Comment by hase1128** [comment]
@hardys 

This PR's target is 4.9.0. Now there is the related BZ.
In this case, this PR is required to merge, right?

**Comment by honza** [comment]
/hold

All but the last commit are already present on the master branch so we don't need to include them. The only commit that we might want to bring in is the one introduced by the PR mentioned in the description.

https://github.com/metal3-io/baremetal-operator/pull/942

Also, may I suggest using the `-x` [flag](https://git-scm.com/docs/git-cherry-pick#Documentation/git-cherry-pick.txt--x) of `git cherry-pick` when backporting code? It aids in any future git archeology endeavours.

**Comment by Hellcatlk** [comment]
> 
> 
> /hold
> 
> All but the last commit are already present on the master branch so we don't need to include them. The only commit that we might want to bring in is the one introduced by the PR mentioned in the description.
> 
> [metal3-io#942](https://github.com/metal3-io/baremetal-operator/pull/942)
> 
> Also, may I suggest using the `-x` [flag](https://git-scm.com/docs/git-cherry-pick#Documentation/git-cherry-pick.txt--x) of `git cherry-pick` when backporting code? It aids in any future git archeology endeavours.

@honza Thanks, done.

**Comment by hardys** [comment]
/retitle Bug 1986656: Fix missing case of BuildRAIDCleanSteps

(This makes it clearer this PR is now just a backport of https://github.com/metal3-io/baremetal-operator/pull/942)

**Comment by hardys** [comment]
/approve

This looks like a valid backport of https://github.com/metal3-io/baremetal-operator/pull/942 to me, thanks!

/cc @andfasano @dtantsur

**Comment by hardys** [comment]
/hold cancel

This is now just a backport of as requested by @honza

**Pull request merged**
