### PR TITLE
Merge upstream 20200713 103725

### PR DESCRIPTION
**Pull request by kirankt**

### CODE REVIEW

**Comment by kirankt** [comment]
Going to wait for couple more PRs upstream to merge before releasing the hold.
/hold

**Comment by dhellmann** [comment]
/hold

we need to merge https://github.com/openshift/cluster-api-provider-baremetal/pull/85 before this

**Comment by hardys** [comment]
https://github.com/openshift/cluster-api-provider-baremetal/pull/85 merged and CI passed so I think this is good to go now

/approve

**Pull request merged**
