### PR TITLE
Vendor the apis submodule

### PR DESCRIPTION
**Pull request by honza**
Downstream builds are failing because without the vendor directory,
`go build` will try to download the modules from the internet.

### CODE REVIEW

**Comment by honza** [comment]
Hmmmm, maybe this isn't it.

The images job [previously passed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_baremetal-operator/161/pull-ci-openshift-baremetal-operator-master-images/1408315130491441152/artifacts/build-logs/baremetal-operator.log) without the vendor subdirectory.

**Comment by jupierce** [comment]
Builds succeeding in CI is not a perfect indicator of whether a component can build downstream in Red Hat's build infrastructure. The latter is restricted from accessing the Internet.

**Comment by honza** [comment]
I was finally able to reproduce the issue from brew in my local environment, and I'm pretty confident that this PR is the correct fix.

**Pull request merged**
