### PR TITLE
[release-4.4] Bug 1840106: Backport get-hardware-details

### PR DESCRIPTION
**Pull request by EgorLu**
This is required for the installer to write the BMH hardware details based on the introspection results from terraform:

https://github.com/openshift/installer/blob/release-4.4/data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh#L39

Currently that script fails, because the entrypoint in the BMO container does not exist, which results in missing data on the baremetal host objects.

### CODE REVIEW

**Comment by hardys** [comment]
Note I debugged this with @EgorLu - we could see that the entrypoint was missing when running master-bmh-update.sh manually so we evidently missed a backport when that was backported in the installer.

There were two other issues which may require installer changes

  * The kubeconfig pointing at localhost didn't find any API listening, so we switched to one referencing the API VIP as a workaround, but this may just be timing related, further testing needed
  * Despite failing to run, the systemd unit didn't show up as failed - I think we need `set -e` in the script, on all branches (I'll push a PR for that)

**Comment by stbenjam** [comment]
Looks like CI is having issues today which is why tests haven't kicked off.

But, very nice find!

/approve
/lgtm

**Comment by dhellmann** [comment]
/hold

this won't pass without pinning the version(s) of the linter(s)

**Comment by dhellmann** [comment]
It looks like gosec changed after v2.3.0 in 55d368f2e55ce21f07fe8da827956ee099e122e4 in a way that is not compatible with go 1.10.

Running gosec by hand against this PR using the hack script, which uses a pre-built image with gosec, produces no errors.

```
$ ./hack/gosec.sh
+ IS_CONTAINER=false
+ CONTAINER_RUNTIME=podman
+ '[' false '!=' false ']'
+ podman run --rm --env IS_CONTAINER=TRUE --volume /home/dhellmann/go/src/github.com/metal3-io/baremetal-operator:/go/src/github.com/metal3-io/baremetal-operator:ro,z --entrypoint sh --workdir /go/src/github.com/metal3-io/baremetal-operator registry.hub.docker.com/securego/gosec:latest /go/src/github.com/metal3-io/baremetal-operator/hack/gosec.sh
+ IS_CONTAINER=TRUE
+ CONTAINER_RUNTIME=podman
+ '[' TRUE '!=' false ]
+ export 'XDG_CACHE_HOME=/tmp/.cache'
+ gosec -severity medium --confidence medium -quiet ./...
```

/override ci/prow/lint

**Comment by stbenjam** [comment]
Thanks @dhellmann! That works for me.

This off our plates now, the patch manager will select this PR for inclusion in an upcoming 4.4.z, and then add the last remaining label (cherry-pick-approved).

**Comment by sdodson** [comment]
@dhellmann @stbenjam Do we not need to update to be compatible with the new gosec or do we feel that change is going to be rolled back? I just want to avoid you being perpetually stuck after this merges.

**Comment by dhellmann** [comment]
> @dhellmann @stbenjam Do we not need to update to be compatible with the new gosec or do we feel that change is going to be rolled back? I just want to avoid you being perpetually stuck after this merges.

We expect to not need to land many changes in this branch in a few weeks, when 4.4 goes out of support. If it becomes a problem for more than 1 PR, we could look at how that job is trying to install gosec and see if we can make it work with the older version of go. Maybe we could change the job to use a pre-built image, for example.

**Pull request merged**
