### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by elfosardo** [comment]
/retest
error getting ansible collections

**Comment by elfosardo** [comment]
/retest
there may be an actual issue with an operator

**Comment by elfosardo** [comment]
/test e2e-metal-ipi-serial-ipv4
inspection timeout

**Comment by elfosardo** [comment]
had a quick look and the errors seem legit
2022-08-08T15:15:48.200116650Z E0808 15:15:48.200105       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1alpha1.HardwareData: failed to list *v1alpha1.HardwareData: hardwaredata.metal3.io is forbidden: User "system:serviceaccount:openshift-machine-api:cluster-baremetal-operator" cannot list resource "hardwaredata" in API group "metal3.io" in the namespace "openshift-machine-api"

**Comment by honza** [comment]
Dependent patch merged

/retest

**Pull request merged**
