### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by zaneb** [comment]
Tests failed with:

```
2021-12-16T12:14:45.013635477Z E1216 12:14:45.013582       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch *v1alpha1.BMCEventSubscription: failed to list *v1alpha1.BMCEventSubscription: bmceventsubscriptions.metal3.io is forbidden: User "system:serviceaccount:openshift-machine-api:cluster-baremetal-operator" cannot list resource "bmceventsubscriptions" in API group "metal3.io" in the namespace "openshift-machine-api"
```

Most likely you need to add the RBAC permissions in CBO before this will work.

**Comment by honza** [comment]
/retest

CBO patch merged

**Pull request merged**
