### PR TITLE
Remove yum install genisoimage from Dockerfile.ocp

### PR DESCRIPTION
**Pull request by honza**
We want to build our images without internet access.

### CODE REVIEW

**Comment by stbenjam** [comment]
> We want to build our images without internet access.

Does this reach out to the internet? It should be available in the yum repos. 

Regardless we can remove this dependency, can we do it upstream too? We can send the configDrive in JSON to Ironic for some time, so we no longer need (nor does BMO even try) to build the ISO image.

**Comment by honza** [comment]
> Does this reach out to the internet? It should be available in the yum repos.

[Yes](http://download.eng.bos.redhat.com/brewroot/work/tasks/9416/35059416/x86_64.log).

> Regardless we can remove this dependency, can we do it upstream too?

No, upstream [doesn't have it](https://github.com/metal3-io/baremetal-operator/blob/master/Dockerfile). 

This is straight up cruft, I think.

**Comment by stbenjam** [comment]
> > Regardless we can remove this dependency, can we do it upstream too?
> 
> No, upstream [doesn't have it](https://github.com/metal3-io/baremetal-operator/blob/master/Dockerfile).
> 
> This is straight up cruft, I think.

LGTM, thanks, let's see CI pass too

**Pull request merged**
