### PR TITLE
[release-4.4] Bug 1832245: Reboot API backport to 4.4

### PR DESCRIPTION
**Pull request by n1r1**
Backport of reboot API that was introduced in https://github.com/metal3-io/baremetal-operator/pull/424 and later merged as part of https://github.com/openshift/baremetal-operator/pull/57

### CODE REVIEW

**Comment by stbenjam** [comment]
There's a CI misconfiguration on the 4.4 branch: https://github.com/openshift/release/pull/9480 will fix it.

**Comment by stbenjam** [comment]
Thanks all!

@n1r1 the final missing label `cherry-pick-approved` will be added by the OCP patch manager when it's selected for a release (should be soon since severity is high).

**Comment by n1r1** [comment]
Sounds good.
Thanks @stbenjam and @mhrivnak !

**Comment by eparis** [comment]
/hold
we do not backport features to z-streams. Please provide justification why we would consider doing this. In a private comment in the BZ might be appropriate since the business justification would obviously contain customer information.

**Comment by n1r1** [comment]
@eparis, I've added justification to bugzilla.
thanks

**Comment by bparees** [comment]
@eparis will be following up on this, but for now it's not being approved pending PM justification.

**Comment by n1r1** [comment]
Per our bugzilla discussion, I'm closing this PR

**Pull request closed without merging**
