### PR TITLE
Use OpenShift forks as dependencies

### PR DESCRIPTION
**Pull request by cynepco3hahue**

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@dhellmann Will do it under the separate PR.

**Comment by cynepco3hahue** [comment]
@dhellmann Done under https://github.com/metal3-io/baremetal-operator/pull/229

**Comment by dhellmann** [comment]
We're waiting to approve this until we understand how https://github.com/metal3-io/baremetal-operator/pull/229 was generated without a newer operator-sdk and whether it is safe to merge based on comments on a similar PR https://github.com/metal3-io/baremetal-operator/pull/228

**Comment by dhellmann** [comment]
What's the status of this? Do we still need it?

**Comment by cynepco3hahue** [comment]
@dhellmann I think yes if it under the OpenShift repository it should use the same dependencies as other machine-api projects.

**Comment by cynepco3hahue** [comment]
@dhellmann Can we merge it?

**Comment by dhellmann** [comment]
> @dhellmann Can we merge it?

Every time I touch the dependencies in this repo it becomes harder and harder to merge patches from upstream. I haven't had the time to sit down and figure out how to resolve that, so I'm reluctant to do anything else that might make it even more work. :-(

**Pull request closed without merging**
