### PR TITLE
Merge upstream 20210311

### PR DESCRIPTION
**Pull request by hardys**
Rebase on upstream metal3-io/baremetal-operator to pick up the most recent changes

### CODE REVIEW

**Comment by Gal-Zaidman** [comment]
/hold

I see that this PR didn't pick the port to controller-runtime to v0.7 https://github.com/metal3-io/baremetal-operator/pull/806
Which was merged a couple of hours after.
This change is blocking a go mod update of the openshift installer.
Can you please include the change as well?

**Comment by hardys** [comment]
> Can you please include the change as well?

Done

/hold cancel

**Comment by honza** [comment]
I think we need https://github.com/openshift/cluster-baremetal-operator/pull/118 to merge first.

**Comment by Gal-Zaidman** [comment]
@hardys e2e-metal-ipi-ovn-ipv6 looks very broken (last time it passed 02-03) is there a different job e2e you can trigger to test the changes?

**Comment by andfasano** [comment]
> @hardys e2e-metal-ipi-ovn-ipv6 looks very broken (last time it passed 02-03) is there a different job e2e you can trigger to test the changes?

Such job is a mandatory one and it is not recommended to be skipped. On the _nightly_ release branch - even though it looks a little bit flaky - it passed few hours ago https://amd64.ocp.releases.ci.openshift.org/releasestream/4.8.0-0.nightly/release/4.8.0-0.nightly-2021-03-14-134919

**Comment by hardys** [comment]
> @hardys e2e-metal-ipi-ovn-ipv6 looks very broken (last time it passed 02-03) is there a different job e2e you can trigger to test the changes?

It's not flaky, I think as @honza mentioned we need openshift/cluster-baremetal-operator#118 to merge, but I forgot to put a hold on this PR

/hold

**Comment by hardys** [comment]
openshift/cluster-baremetal-operator#118 is now passing CI, @honza PTAL, thanks!

**Comment by honza** [comment]
I just LGTM'd https://github.com/openshift/cluster-baremetal-operator/pull/118 so now it's up to CI.

**Comment by hardys** [comment]
Ok we now need the CBO change to make it into a 4.8.0-0.ci Accepted build, then hopefully the retests will work

**Pull request merged**
