### PR TITLE
Bug 1927678: Backporting BMO extensions to support different reboot modes

### PR DESCRIPTION
**Pull request by rdoxenham**
In this PR I'm pulling metal3-io/baremetal-operator/pull/795 back into openshift/baremetal-operator to allow this to be eventually backported into stable releases. This PR adds additional capabilities to the baremetal operator to support a variety of reboot modes, and was originally implemented to support hard reboots, e.g. for fencing/high-availability purposes.

### CODE REVIEW

**Comment by stbenjam** [comment]
Would you mind filing a 4.8 bug and putting "Bug XYZ: " in the PR title? It's required to backport. It'll also make your life a lot easier. After this merges, you can do `/cherry-pick release-4.7` and it will do all the needed things including creating a 4.7 BZ.

**Comment by rdoxenham** [comment]
> Would you mind filing a 4.8 bug and putting "Bug XYZ: " in the PR title? It's required to backport. It'll also make your life a lot easier. After this merges, you can do `/cherry-pick release-4.7` and it will do all the needed things including creating a 4.7 BZ.

@stbenjam absolutely! thanks a lot :)

**Comment by honza** [comment]
@rdoxenham Please hold off on backporting to 4.7 until #127 merges

**Comment by rdoxenham** [comment]
> @rdoxenham Please hold off on backporting to 4.7 until #127 merges

@honza no worries, thanks!

**Comment by stbenjam** [comment]
/test e2e-metal-ipi

IPv6 is currently broken: https://bugzilla.redhat.com/show_bug.cgi?id=1934107, and looks like IPv4 is hitting a known flake.

**Comment by stbenjam** [comment]
> @rdoxenham Please hold off on backporting to 4.7 until #127 merges

Oops right, we'll retry the chery-pick when that merges :)

**Comment by rdoxenham** [comment]
> /cherry-pick release-4.7

Do we have to do this manually now that the first time it failed? The bot doesn't seem to be picking up the request.

**Comment by rdoxenham** [comment]
Backport to 4.7 is now in baremetal-operator/pull/130

**Pull request merged**
