### PR TITLE
NO-ISSUE: Sync with upstream

### PR DESCRIPTION
**Pull request by iurygregory**

### CODE REVIEW

**Comment by dtantsur** [comment]
Maybe revert the `go.mod` version change for now?

**Comment by iurygregory** [comment]
proxyconnect tcp: dial tcp 128.31.20.106:8040: i/o timeout

/test e2e-metal-ipi-virtualmedia

**Comment by iurygregory** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-sdn-bm

**Comment by iurygregory** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ovn-single-node-live-iso
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-serial-virtalmedia

**Comment by iurygregory** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-serial-virtalmedia

**Comment by iurygregory** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-serial-virtualmedia

**Pull request merged**
