### PR TITLE
Merge upstream 2021-02-11

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by dtantsur** [comment]
Would it be possible to also include the changes from https://github.com/metal3-io/baremetal-operator/pull/786 or should I propose them separately?

**Comment by honza** [comment]
> Would it be possible to also include the changes from metal3-io#786 or should I propose them separately?

Certainly. See above.

**Comment by hardys** [comment]
https://github.com/openshift/cluster-baremetal-operator/pull/105 is now passing CI, so we need someone to add lgtm to that, then we can retest this PR

**Comment by dtantsur** [comment]
/retest

https://github.com/openshift/cluster-baremetal-operator/pull/105 merged

**Pull request merged**
