### PR TITLE
[release-4.13] OCPBUGS-17229: Set minimum TLS version for webhook to 1.2

### PR DESCRIPTION
**Pull request by zaneb**

### CODE REVIEW

**Comment by honza** [comment]
The commit doesn't match the PR description.

**Comment by zaneb** [comment]
> The commit doesn't match the PR description.

Thanks, I definitely forced-pushed something intended for another PR to the wrong branch :facepalm: 
I was wondering where that change had gone! Fixed now.

**Comment by zaneb** [comment]
/assign @dtantsur 
@pamoedom need cherry-pick-approved on this PR please

**Pull request merged**
