### PR TITLE
[preview] merge upstream 2021-02-01

### PR DESCRIPTION
**Pull request by honza**
Here is [the commit without the vendor update](https://github.com/honza/baremetal-operator/commit/ec18e6ecc7c444d6c17c7daeb79c10f01defe17e).

cc @stbenjam

### CODE REVIEW

**Comment by stbenjam** [comment]
/test e2e-metal-assisted

Not sure if that one's here, but we probably want to check it.

**Comment by honza** [comment]
https://github.com/openshift/cluster-baremetal-operator/pull/100 is now merged so let's try a fresh build

/retest

**Comment by honza** [comment]
#125

**Comment by honza** [comment]
Superseded by #125

**Pull request closed without merging**
