### PR TITLE
Merge upstream 2021-04-06

### PR DESCRIPTION
**Pull request by honza**
cc @hardys

### CODE REVIEW

**Comment by hardys** [comment]
Looking at the must-gather from one of the failing jobs, it doesn't seem to be related to this change - the BMO started and provisioned the workers AFAICS:

```
2021-04-06T17:48:08.509792176Z {"level":"info","ts":1617731288.5097504,"logger":"controllers.BareMetalHost","msg":"verified access to the BMC","baremetalhost":"openshift-machine-api/ostest-worker-0","provisioningState":"provisioned"}
```

**Comment by hardys** [comment]
It seems suspicious that all the tests have failed several times, but AFAICS from the logs the workers did get provisioned and there's no error output in the BMO logs e.g:

```
2021-04-08T00:27:36.294702915Z {"level":"info","ts":1617841656.2936947,"logger":"controllers.BareMetalHost","msg":"verified access to the BMC","baremetalhost":"openshift-machine-api/ostest-worker-0","provisioningState":"provisioned"}
2021-04-08T00:27:36.357499265Z {"level":"info","ts":1617841656.3574355,"logger":"controllers.BareMetalHost","msg":"done","baremetalhost":"openshift-machine-api/ostest-worker-0","provisioningState":"provisioned","requeue":true,"after":60}
```

**Comment by stbenjam** [comment]
` [sig-installer][Feature:baremetal] Baremetal platform should have baremetalhost resources [Suite:openshift/conformance/parallel]` seems to be consistently failing, that is concerning and needs looking at

**Comment by hardys** [comment]
That's odd - I see them in the must-gather, and the BMO says the workers were deployed :thinking:

**Comment by zaneb** [comment]
I think metal3-io/baremetal-operator#849 should fix this.

**Comment by stbenjam** [comment]
Looks like upstream prow will be broken until at least tomorrow, we should probably just land this and carry Zane's patch here.

**Comment by zaneb** [comment]
I agree with Stephen's suggestion. Carrying the patch until the upstream CI is stood up again won't hurt. CI here shows that it fixes the bug, so nothing is likely to change in the upstream PR and the subsequent merge will be trivial.
/hold cancel

**Pull request merged**
