### PR TITLE
Bug 1924475: upgrade k8s/api to v0.21

### PR DESCRIPTION
**Pull request by asalkeld**

### CODE REVIEW

**Comment by zaneb** [comment]
Did you run `go mod vendor`? Go modules surprise me quite often, but I'm surprised not to see any code changes in this PR.

**Comment by stbenjam** [comment]
Yea we need to run go mod vendor and go mod tidy, sorry I missed that

/hold

**Comment by stbenjam** [comment]
There's no code changes. go mod tidy/go mod vendor says this is correct.


```
$ go mod verify
all modules verified
```

Keep in mind go only vendors the code it's using, so the bump from 0.20.0 to 0.20.1 may not have resulted in any files changed that we use? I'm not entirely sure.

**Comment by zaneb** [comment]
Looks like the patch is correct as far as it goes.
It appears that kubernetes/apimachinery has not updated the dependency on gogo/protobuf 1.3.1 [in v0.20.1](https://github.com/kubernetes/apimachinery/blob/v0.20.1/go.mod#L13), or indeed in [anywhere in the 0.20 branch](https://github.com/kubernetes/apimachinery/blob/release-1.20/go.mod#L13) up to and including [v0.20.6rc](https://github.com/kubernetes/apimachinery/blob/v0.20.6-rc.0/go.mod#L13), it's [fixed](https://github.com/kubernetes/apimachinery/commit/9812d821fcf5b9a590d2954fac828dd3b2cf8db5) only in 0.21.
Until they backport that fix then nothing we do will have any effect on fixing the bug.

**Comment by zaneb** [comment]
In summary, we need to upgrade to 0.21; this upgrades to 0.20.1; and the headline says 0.2.1.

**Pull request closed without merging**
