### PR TITLE
Bug 1781833: Cherry-pick virtual media changes to 4.3

### PR DESCRIPTION
**Pull request by stbenjam**
This cherry-picks the features that enable management of virtual media for Redfish, iLO5, and iDRAC to OpenShift 4.3 release branch of baremetal-operator.

### CODE REVIEW

**Comment by stbenjam** [comment]
@dhellmann @russellb Which component should I file a BZ under for this cherry-picking?

**Comment by dhellmann** [comment]
> @dhellmann @russellb Which component should I file a BZ under for this cherry-picking?

I don't know, I've never had to do this part of the process.

**Comment by stbenjam** [comment]
Ok so we may just be missing a component. It’s odd, there’s no cluster api top level component or similar to put BMO under.

**Comment by dhellmann** [comment]
> Ok so we may just be missing a component. It’s odd, there’s no cluster or machine api top level component or similar to put BMO under, which is my guess would be the best place.

According to the [Jira sync script](https://github.com/openshift-metal3/jira-sync/blob/master/sync.sh#L147) we may just be using the product "Kubernetes-native Infrastructure" and component "Deployment".

**Pull request merged**
