### PR TITLE
Bug 1936407: Backport of BMO code to 4.7 to support different reboot modes

### PR DESCRIPTION
**Pull request by rdoxenham**
Here we're pulling in the BMO code that supports flexible reboot modes to be issued by clients, allowing soft reboots when required, e.g. maintenance, and hard reboots when remediation and workload recovery needs to take place. This code originally landed in metal3-io/baremetal-operator/795, backported to OpenShift in openshift/baremetal-operator/128, and now back to 4.7.z. 

NOTE: This is an alternative proposal that has dealt with the conflicts, and doesn't pull in additional commits that we had with #130.

### CODE REVIEW

**Comment by hardys** [comment]
/retitle Bug 1936407: Backport of BMO code to 4.7 to support different reboot modes

**Comment by stbenjam** [comment]
You should be all set.  The final step is the OpenShift patch manager will select it for an upcoming z-Stream. Since the severity is high, it should be soon but may take a couple of weeks.

**Comment by rdoxenham** [comment]
Please make sure this gets backported/selected for 4.7.z at the same time as https://github.com/openshift/cluster-api-provider-baremetal/pull/144

**Pull request merged**
