### PR TITLE
Merge with upstream metal3-io/baremetal-operator

### PR DESCRIPTION
**Pull request by beekhof**
Resolve merge conflicts

### CODE REVIEW

**Comment by beekhof** [comment]
Looks like some of the dependancies @n1r1 added got lost in the Gopk.toml -> go.mod transition. Will fix

**Comment by beekhof** [comment]
Test failures seem related to this sequence of commits:

 * Honza Pokorny (6 weeks ago) c5b42d62: Export cache dir in gofmt 
 * Honza Pokorny (7 weeks ago) 0af5bf7d: Unset GOFLAGS 
 * Honza Pokorny (10 weeks ago) 580210b1: Update dockerfile to build from golang 1.13 
 * Honza Pokorny (10 weeks ago) eb7b204d: Update travis to use go modules 
 * Honza Pokorny (6 weeks ago) 8e38ebd3: Upgrade operator-sdk 
 * Honza Pokorny (6 weeks ago) 0f8c3f46: Remove Gopkg files and vendor directory 
 * Honza Pokorny (6 weeks ago) ca00c0bb: Migrate to go modules 

@honza can you share the secret sauce that allows upstream to build without a vendor directory?

**Comment by stbenjam** [comment]
I think to make this work reliably, you'll need to run `go mod vendor` and generate the vendor/ directory for the openshift fork.  CI can't download the modules on the fly.

I assume it probably needs to be an OCP-only thing, since I wouldn't expect upstream to carry milions of lines of vendored code because of a limitation on our CI servers.

**Comment by stbenjam** [comment]
@hardys @dhellmann @russellb Could one of you approve please? Thanks!

**Pull request merged**
