### PR TITLE
Bug 1986654: Auto cleaning step in Prepare stage failed

### PR DESCRIPTION
**Pull request by Hellcatlk**
I will pick up the upstream PRs after that has been merged, and will add that commits into this one. 
URL of upstream PRs are as follows.
 - https://github.com/metal3-io/baremetal-operator/pull/929

Therefore, please pend the review of this PR.

### CODE REVIEW

**Comment by dtantsur** [comment]
/ok-to-test

As I mentioned on the upstream review, it's better to make the Ironic RAID implementation to wait for the machine to be ready.

**Comment by hase1128** [comment]
@rhjanders 
Hi, can someone in RH add lgtm and approve labels?

**Pull request merged**
