### PR TITLE
OCPBUGS-12363: release-4.13: Use same settings for provisioner and controller logs

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by zaneb** [comment]
Logs look correct in CI now.

/retest-required

**Comment by honza** [comment]
@zaneb It looks like it needs your attention at this point. *Needs staff-eng-approved label.*

**Comment by zaneb** [comment]
I'm inclined to leave it for a z-stream release at this point since it's not a release blocker, but I've asked for more info on when to apply that label.

**Pull request merged**
