### PR TITLE
Bug 1862980: Add support for http_basic auth for ironic and inspector

### PR DESCRIPTION
**Pull request by zaneb**
Merge upstream feature from metal3-io/baremetal-operator#601

### CODE REVIEW

**Comment by dhellmann** [comment]
/lgtm

The upstream PR is approved to merge but I'll leave the hold here until it does.

**Comment by hardys** [comment]
/retitle Bug 1862980: Add support for http_basic auth for ironic and inspector

**Comment by zaneb** [comment]
Merged upstream.
/hold cancel

**Pull request merged**
