### PR TITLE
NO-ISSUE: Upstream Sync nov8

### PR DESCRIPTION
**Pull request by iurygregory**

### CODE REVIEW

**Comment by iurygregory** [comment]
ok the failure is valid, we don't seem to have go 1.22.8 available for our testing, 
`go: go.mod requires go >= 1.22.8 (running go 1.22.7; GOTOOLCHAIN=local)`
should we just remove the commit from the sync? cc @dtantsur @honza

**Comment by iurygregory** [comment]
Let's see how it goes after adding a revert to the golang bump to 1.22.8

**Comment by iurygregory** [comment]
Ok, seems like it's https://github.com/metal3-io/baremetal-operator/commit/400a882288d3788c220e9c5b50f92c2a65b6e1db that I need to remove. too many conflicts, let me try to figure out

**Comment by iurygregory** [comment]
Instead of going with removing commits, I decided to create a new one downgrading the 1.22.8 version to 1.22.7 in the necessary files to make CI happy

**Comment by rhjanders** [comment]
Thank you Iury.
CI pass
Start/end commits match what I expected
/lgtm

**Pull request merged**
